"use client";

import { FormEvent, useEffect, useState } from "react";
import type { Complaint } from "@/types/citizen";

type CitizenUser = { fullName: string; email: string | null; mobile: string | null; stateId: string | null; districtId: string | null; cityId: string | null; wardId: string | null; address: string | null };

export function NotificationsPanel({ complaints }: { complaints: Complaint[] }) {
  return <section className="account-page"><div className="page-title"><p className="eyebrow">CITIZEN PORTAL · LIVE UPDATES</p><h1>Notifications</h1><p>Updates are generated from your complaint activity and refreshed automatically.</p></div><div className="notification-list">{complaints.length === 0 ? <div className="empty-account"><b>No notifications yet</b><span>Your complaint updates will appear here.</span></div> : complaints.map((complaint) => <article className="notification-item" key={complaint.id}><span className="notification-dot">●</span><div><b>{complaint.reference} · {complaint.status}</b><p>{complaint.title}</p><small>Last updated {new Date(complaint.updatedAt).toLocaleString()}</small></div></article>)}</div></section>;
}

export function WardProblemsPanel({ complaints }: { complaints: Complaint[] }) {
  const [items, setItems] = useState(complaints.filter((complaint) => complaint.status !== "RESOLVED" && complaint.status !== "REJECTED"));
  useEffect(() => { setItems(complaints.filter((complaint) => complaint.status !== "RESOLVED" && complaint.status !== "REJECTED")); }, [complaints]);
  const sign = async (complaint: Complaint) => { const response = await fetch(`/api/complaints/${complaint.id}/sign`, { method: "POST" }); const data = await response.json(); if (!response.ok) return; setItems((current) => current.map((item) => item.id === complaint.id ? { ...item, signatureCount: data.signatureCount, signedByMe: true } : item)); };
  return <section className="account-page"><div className="page-title"><p className="eyebrow">YOUR WARD · CIVIC PETITIONS</p><h1>Ward problems</h1><p>Support an existing problem so the ward team sees community demand without duplicate complaints.</p></div><div className="petition-list">{items.length === 0 ? <div className="empty-account"><b>No open ward problems yet</b><span>New geotagged complaints from your ward will appear here.</span></div> : items.map((complaint) => <article className="petition-row" key={complaint.id}><div><div className="card-top"><span className="status amber">{complaint.status}</span><span>{complaint.reference}</span></div><h3>{complaint.title}</h3><p className="location">⌖ {complaint.address}</p><small>{complaint.signatureCount} petition signatures · updated {new Date(complaint.updatedAt).toLocaleDateString()}</small></div><div className="petition-actions"><button className="primary-cta" type="button" disabled={complaint.signedByMe} onClick={() => sign(complaint)}>{complaint.signedByMe ? "Signed ✓" : "Sign petition"}</button><button className="secondary-button" type="button" onClick={() => downloadPetition(complaint)}>Download petition</button></div></article>)}</div></section>;
}

function downloadPetition(complaint: Complaint) {
  const escapeHtml = (value: string) => value.replace(/[&<>\'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Civic Petition ${escapeHtml(complaint.reference)}</title><style>body{font-family:Arial,sans-serif;color:#182b2b;max-width:760px;margin:0 auto;padding:56px;line-height:1.55}header{border-bottom:3px solid #27766f;padding-bottom:20px}h1{font-size:30px;margin:8px 0}h2{font-size:18px;margin-top:30px;color:#27766f}.eyebrow{font-size:11px;letter-spacing:2px;color:#27766f;font-weight:bold}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px;background:#f1f7f5;padding:18px;margin-top:24px}.meta span{display:block;font-size:12px;color:#637572}.meta b{display:block;font-size:14px}.statement{border-left:4px solid #ef8469;padding:10px 18px;margin:20px 0}footer{border-top:1px solid #dce5e2;margin-top:50px;padding-top:16px;color:#637572;font-size:11px}</style></head><body><header><div class="eyebrow">SOCIOX AI CIVIC PLATFORM · COMMUNITY PETITION</div><h1>Petition for Civic Action</h1><p>Request for review and resolution of a reported issue in the local ward.</p></header><div class="meta"><div><span>Complaint ID</span><b>${escapeHtml(complaint.reference)}</b></div><div><span>Current status</span><b>${escapeHtml(complaint.status)}</b></div><div><span>Issue category</span><b>${escapeHtml(complaint.category)}</b></div><div><span>Location</span><b>${escapeHtml(complaint.address)}</b></div><div><span>Community signatures</span><b>${complaint.signatureCount}</b></div><div><span>Last updated</span><b>${escapeHtml(new Date(complaint.updatedAt).toLocaleString())}</b></div></div><h2>Petition statement</h2><div class="statement">We, the residents and affected members of this ward, request that the appropriate civic authority review and resolve: <strong>${escapeHtml(complaint.title)}</strong>.</div><p>The issue is recorded in the SocioX AI civic complaint platform. Community signatures indicate public support for transparent review, assignment, and resolution.</p><h2>Reported issue</h2><p>${escapeHtml(complaint.description)}</p><footer>This petition contains civic issue information only. Personal contact details are not included.<br>Generated by SocioX AI Civic Platform · ${escapeHtml(new Date().toLocaleString())}</footer></body></html>`;
  const url = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = `petition-${complaint.reference}.html`; link.click(); URL.revokeObjectURL(url);
}

export function ProfilePanel({ user }: { user: CitizenUser | null }) {
  return <section className="account-page"><div className="page-title"><p className="eyebrow">CITIZEN PORTAL · ACCOUNT</p><h1>Your profile</h1><p>Your identity and registration location used for civic routing.</p></div><div className="profile-grid"><div className="profile-hero"><span className="profile-large-avatar">{(user?.fullName ?? "User").slice(0, 2).toUpperCase()}</span><h2>{user?.fullName ?? "Citizen"}</h2><p>{user?.email ?? user?.mobile ?? "No contact saved"}</p></div><div className="profile-details"><ProfileField label="State ID" value={user?.stateId} /><ProfileField label="District ID" value={user?.districtId} /><ProfileField label="Town / City ID" value={user?.cityId} /><ProfileField label="Ward ID" value={user?.wardId} /><ProfileField label="Address" value={user?.address} /></div></div></section>;
}
function ProfileField({ label, value }: { label: string; value: string | null | undefined }) { return <div className="profile-field"><small>{label}</small><b>{value || "Not provided"}</b></div>; }

export function HelpCenter() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); event.currentTarget.reset(); };
  return <section className="account-page"><div className="page-title"><p className="eyebrow">SOCIOX AI · SUPPORT</p><h1>Help center</h1><p>Find quick answers or send a message to the citizen support team.</p></div><div className="help-grid"><div className="help-faq"><HelpItem title="How do I report an issue?" detail="Open Report an issue, add a title, address, description, and optional GPS/photo evidence, then submit." /><HelpItem title="How accurate is GPS?" detail="The map shows the device-reported accuracy in meters and keeps updating while location access is enabled." /><HelpItem title="How do I track a complaint?" detail="Open My complaints to see the latest status, reference number, location, and update time." /></div><form className="help-form" onSubmit={submit}><b>Contact support</b><label>Subject<input name="subject" placeholder="What do you need help with?" required /></label><label>Message<textarea name="message" placeholder="Describe the issue..." required /></label>{sent && <div className="success-note">Your support request has been recorded for this session.</div>}<button className="primary-cta" type="submit">Send message →</button></form></div></section>;
}
function HelpItem({ title, detail }: { title: string; detail: string }) { return <article className="help-item"><b>{title}</b><p>{detail}</p></article>; }
