"use client";

import { useState } from "react";
import type { Complaint } from "@/types/citizen";

type CitizenUser = { id: string; fullName: string; wardId: string | null };

function statusClass(status: string) {
  if (status === "RESOLVED") return "teal";
  if (status === "IN PROGRESS" || status === "IN REVIEW") return "amber";
  return "teal";
}

export function RealtimeCitizenDashboard({ user, complaints, onReport, onMap, onComplaints }: { user: CitizenUser | null; complaints: Complaint[]; onReport: () => void; onMap: () => void; onComplaints: () => void }) {
  const ownComplaints = complaints.filter((complaint) => complaint.citizenId === user?.id);
  const activeCount = ownComplaints.filter((complaint) => !["RESOLVED", "REJECTED"].includes(complaint.status)).length;
  const resolvedCount = ownComplaints.filter((complaint) => complaint.status === "RESOLVED").length;
  return <><section className="welcome"><div><p className="eyebrow">CITIZEN PORTAL · LIVE PERSONAL DASHBOARD</p><h1>Welcome, {user?.fullName ?? "Citizen"}.<br /><em>Your civic network.</em></h1><p className="intro">Your dashboard refreshes automatically. {user?.wardId ?? "Your selected ward"} is connected to local civic updates.</p></div><button className="primary-cta" onClick={onReport}>Report an issue <span>→</span></button></section><section className="stats"><Stat label="MY REPORTS" value={String(ownComplaints.length).padStart(2, "0")} note="Synced from your account" /><Stat label="ACTIVE ISSUES" value={String(activeCount).padStart(2, "0")} note="Awaiting action" /><Stat label="RESOLVED" value={String(resolvedCount).padStart(2, "0")} note="Completed cases" /></section><section className="citizen-live"><span>◉ LIVE SYNC · 10 SEC</span><b>{ownComplaints[0]?.reference ?? "No reports yet"} · {ownComplaints[0]?.title ?? "Your civic activity will appear here"}</b><small>{ownComplaints[0]?.status ?? "Create a report to start tracking it."}</small></section><section className="section-head"><div><p className="eyebrow">YOUR ACTIVITY</p><h2>Recent complaints</h2></div><button className="text-button" onClick={onComplaints}>View all →</button></section><div className="complaint-grid">{ownComplaints.slice(0, 4).map((complaint) => <ComplaintCard complaint={complaint} key={complaint.id} />)}{ownComplaints.length === 0 && <button className="complaint-card new-card" onClick={onReport}>✦<b>Report your first issue</b><span>Pin it to the real civic map</span></button>}</div><section className="community-band"><span className="community-icon">⌖</span><div><p className="eyebrow">YOUR COMMUNITY</p><h3>See what your neighbours are reporting</h3><p>{user?.wardId ?? "Your ward"} · live complaint locations and status updates</p></div><button className="outline-button" onClick={onMap}>Open real map →</button></section></>;
}

function ComplaintCard({ complaint }: { complaint: Complaint }) { return <article className="complaint-card"><div className="card-top"><span className={`status ${statusClass(complaint.status)}`}>{complaint.status}</span><span>{complaint.reference}</span></div><h3>{complaint.title}</h3><p className="location">⌖ {complaint.address}</p><div className="card-bottom"><span>{new Date(complaint.updatedAt).toLocaleDateString()}</span><span>{complaint.category}</span></div></article>; }
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <div className="stat"><span className="stat-symbol">▤</span><p>{label}</p><strong>{value}</strong><small>{note}</small></div>; }

export function ComplaintListLive({ complaints, onReport }: { complaints: Complaint[]; onReport: () => void }) { const [selected, setSelected] = useState<Complaint | null>(null); if (selected) return <ComplaintDetail complaint={selected} onBack={() => setSelected(null)} />; return <><section className="section-head page-title"><div><p className="eyebrow">CASEWORK · LIVE</p><h1>My complaints</h1><p>Your persisted cases and their latest server status.</p></div><button className="primary-cta" onClick={onReport}>Report an issue →</button></section><div className="complaint-grid">{complaints.map((complaint) => <button className="complaint-card complaint-card-button" onClick={() => setSelected(complaint)} key={complaint.id}><ComplaintCard complaint={complaint} /></button>)}{complaints.length === 0 && <p>No complaints yet.</p>}</div></>; }

function ComplaintDetail({ complaint, onBack }: { complaint: Complaint; onBack: () => void }) { return <section className="complaint-detail"><button className="back-link" onClick={onBack}>← Back to my complaints</button><div className="detail-header"><div><p className="eyebrow">CIVIC COMPLAINT · {complaint.reference}</p><h1>{complaint.title}</h1><p className="location">⌖ {complaint.address}</p></div><span className={`status ${statusClass(complaint.status)}`}>{complaint.status}</span></div><div className="detail-grid"><section className="detail-panel"><DetailRow label="Complaint ID" value={complaint.reference} /><DetailRow label="Submitted" value={new Date(complaint.createdAt).toLocaleString()} /><DetailRow label="Last updated" value={new Date(complaint.updatedAt).toLocaleString()} /><DetailRow label="Issue category" value={complaint.category} /><DetailRow label="Community signatures" value={String(complaint.signatureCount)} /><DetailRow label="Location" value={complaint.address} /></section><section className="detail-panel detail-description"><p className="eyebrow">DESCRIPTION</p><p>{complaint.description}</p>{complaint.latitude !== null && complaint.longitude !== null && <small>GPS coordinates: {complaint.latitude.toFixed(5)}, {complaint.longitude.toFixed(5)}</small>}</section></div><div className="detail-actions"><button className="primary-cta" onClick={() => downloadComplaint(complaint)}>Download complaint</button><button className="secondary-button" onClick={() => window.print()}>Print complaint</button></div></section>; }
function DetailRow({ label, value }: { label: string; value: string }) { return <div className="detail-row"><small>{label}</small><b>{value}</b></div>; }
function downloadComplaint(complaint: Complaint) { const escapeHtml = (value: string) => value.replace(/[&<>\'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(complaint.reference)} · SocioX AI</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:auto;padding:48px;color:#182b2b;line-height:1.6}header{border-bottom:3px solid #27766f;padding-bottom:18px}h1{font-size:28px}.eyebrow{color:#27766f;font-size:11px;letter-spacing:2px;font-weight:bold}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px;background:#f1f7f5;padding:18px}.meta span{display:block;color:#637572;font-size:11px}.meta b{display:block}footer{margin-top:40px;border-top:1px solid #dce5e2;padding-top:14px;color:#637572;font-size:11px}</style></head><body><header><div class="eyebrow">SOCIOX AI CIVIC PLATFORM · COMPLAINT RECORD</div><h1>${escapeHtml(complaint.title)}</h1><p>${escapeHtml(complaint.reference)} · ${escapeHtml(complaint.status)}</p></header><div class="meta"><div><span>Category</span><b>${escapeHtml(complaint.category)}</b></div><div><span>Location</span><b>${escapeHtml(complaint.address)}</b></div><div><span>Submitted</span><b>${escapeHtml(new Date(complaint.createdAt).toLocaleString())}</b></div><div><span>Updated</span><b>${escapeHtml(new Date(complaint.updatedAt).toLocaleString())}</b></div><div><span>Signatures</span><b>${complaint.signatureCount}</b></div><div><span>Coordinates</span><b>${complaint.latitude === null ? "Not captured" : `${complaint.latitude.toFixed(5)}, ${complaint.longitude?.toFixed(5)}`}</b></div></div><h2>Description</h2><p>${escapeHtml(complaint.description)}</p><footer>Personal contact details are excluded from this downloaded record.<br>Generated by SocioX AI Civic Platform · ${escapeHtml(new Date().toLocaleString())}</footer></body></html>`; const url = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `${complaint.reference}-complaint.html`; link.click(); URL.revokeObjectURL(url); }

export function ReportComplaint({ onBack, onCreated }: { onBack: () => void; onCreated: (complaint: Complaint) => void }) {
  const [title, setTitle] = useState(""); const [category, setCategory] = useState("Roads & Transportation"); const [address, setAddress] = useState(""); const [description, setDescription] = useState(""); const [photoName, setPhotoName] = useState(""); const [coordinates, setCoordinates] = useState<[number, number] | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [duplicate, setDuplicate] = useState<Complaint | null>(null); const [signed, setSigned] = useState(false);
  const useGps = () => { if (!navigator.geolocation) { setError("Location is not supported by this browser."); return; } navigator.geolocation.getCurrentPosition((position) => setCoordinates([position.coords.latitude, position.coords.longitude]), () => setError("Location permission was not granted."), { enableHighAccuracy: true, timeout: 10_000 }); };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setDuplicate(null); setSaving(true); try { const response = await fetch("/api/complaints", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, category, address, description, photoName, latitude: coordinates?.[0], longitude: coordinates?.[1] }) }); const data = await response.json(); if (response.status === 409 && data.duplicate) { setDuplicate(data.duplicate); return; } if (!response.ok) throw new Error(data.error ?? "Unable to create complaint."); onCreated(data.complaint); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Unable to create complaint."); } finally { setSaving(false); } };
  const signPetition = async () => { if (!duplicate) return; const response = await fetch(`/api/complaints/${duplicate.id}/sign`, { method: "POST" }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "Unable to sign petition."); return; } setSigned(true); };
  return <div className="form-page"><button className="back-link" onClick={onBack}>← Back to overview</button><div className="form-heading"><p className="eyebrow">NEW CIVIC REPORT · LIVE SUBMISSION</p><h1>Turn evidence into<br /><em>action.</em></h1><p>Your report is saved to your account and appears on the live complaint map.</p></div>{duplicate && <section className="petition-card"><p className="eyebrow">DUPLICATE CHECK</p><h2>This issue is already reported.</h2><p><b>{duplicate.reference}</b> · {duplicate.title}</p><span>{duplicate.signatureCount} citizens have signed this ward petition.</span>{signed ? <strong>✓ Your signature was recorded.</strong> : <button className="primary-cta" type="button" onClick={signPetition}>Sign petition instead →</button>}</section>}<form onSubmit={submit}><label>Issue title <small>Required</small><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Deep pothole on Main Road" required /></label><div className="form-row"><label>Location <small>Required</small><div className="input-row"><span>⌖</span><input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Enter the issue address" required /><button type="button" onClick={useGps}>Use GPS</button></div>{coordinates && <small className="gps-state">GPS captured: {coordinates[0].toFixed(5)}, {coordinates[1].toFixed(5)}</small>}</label><label>Issue type<select value={category} onChange={(event) => setCategory(event.target.value)}><option>Roads & Transportation</option><option>Water & Drainage</option><option>Waste Management</option><option>Electricity & Street Lighting</option><option>Public Health & Safety</option></select></label></div><label>Description <small>Required</small><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Tell us what is happening..." minLength={3} maxLength={5000} required /><span className="char-count">{description.length}/5000</span></label><label>Photo <small>Optional</small><input type="file" accept="image/*" onChange={(event) => setPhotoName(event.target.files?.[0]?.name ?? "")} /></label>{error && <div className="auth-error">{error}</div>}<div className="form-footer"><small>{saving ? "Saving securely..." : "Your report will be visible in your complaint feed."}</small><button className="primary-cta" type="submit" disabled={saving}>{saving ? "Submitting..." : "Submit complaint →"}</button></div></form></div>;
}
