"use client";

import { useMemo, useState } from "react";
import type { Complaint } from "@/types/citizen";
import { CitizenMap } from "@/components/citizen/CitizenMap";

export function OperationsMap({ complaints, departmentView = false, wardCenter, wardRadiusKm = 2.5 }: { complaints: Complaint[]; departmentView?: boolean; wardCenter?: [number, number]; wardRadiusKm?: number }) {
  const [status, setStatus] = useState("ALL");
  const [category, setCategory] = useState("ALL");
  const filtered = useMemo(() => complaints.filter((complaint) => (status === "ALL" || complaint.status === status) && (category === "ALL" || complaint.category === category)), [complaints, status, category]);
  const categories = [...new Set(complaints.map((complaint) => complaint.category))];
  return <section className="operations-map-page"><div className="map-page-heading"><div><p className="eyebrow">{departmentView ? "DEPARTMENT OPERATIONS · LIVE GIS" : "CITIZEN PORTAL · LIVE GIS"}</p><h1>{departmentView ? "See every issue in your district." : "Issues around your community."}</h1><p>{departmentView ? "Filter, inspect, and prioritize geotagged civic problems for department action." : "Explore reported problems, petition activity, and your live position."}</p></div><span className="map-live-state">● {filtered.length} visible issues</span></div><div className="map-controls"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option><option>SUBMITTED</option><option>IN REVIEW</option><option>VERIFIED</option><option>IN PROGRESS</option><option>RESOLVED</option><option>REJECTED</option></select></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="ALL">All departments</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><div className="map-legend"><span><i className="legend-dot open" />Open</span><span><i className="legend-dot resolved" />Resolved</span><span><i className="legend-dot user" />Your position</span></div></div><div className="operations-map-grid"><CitizenMap complaints={filtered} trackUser={!departmentView} wardCenter={wardCenter} wardRadiusKm={wardRadiusKm} /><aside className="map-issue-list"><div className="map-list-header"><b>{departmentView ? "District issue queue" : "Nearby issue queue"}</b><small>Updates with live complaint data</small></div>{filtered.length === 0 ? <p className="audit-empty">No issues match these filters.</p> : filtered.slice(0, 12).map((complaint) => <article className="map-issue" key={complaint.id}><div><b>{complaint.reference}</b><h3>{complaint.title}</h3><small>{complaint.category} · {complaint.status}</small><span>⌖ {complaint.address}</span></div><strong>{complaint.signatureCount}</strong></article>)}</aside></div></section>;
}
